services: # docker compose expects
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PORT=8000
    env_file:
      - .env.sample
    volumes:
      - ./backend/src:/app # volumes dont care about the dockerignore it just mounts the entire volume in the docker container ( and its two-way sync - i.e. reflect changes from local to the container and vice versa )
    develop:
      watch:
        - action: rebuild
          path: backend/requirements.txt
        - action: rebuild
          path: backend/Dockerfile
        # - action: sync
        - action: restart # sync cares about docker ignore and its one way sync ( will watch reflect changes from local to the container )
          path: backend/src/
          # target: /app

  static_html: # custom key name
    build:
      context: ./static_html
      dockerfile: static.Dockerfile
    ports:
      - 8000:8000
      - 3000:8000
    command: python -m http.server 8000
    volumes:
      - ./static_html/src:/app
